adopt initial project governance
k8sgateway/community pull request #19
Opened 2024-11-21 21:54 UTC by ilrudie

This is a new draft of project governance, based partially on the previous draft(#5) which was not accepted. It strives to shortcoming noticed during the first review and initial voting process. It derives more form and verbiage from upstream governance documents taking inspiration and passages from the [CNCF templates](https://github.com/cncf/project-template).

2024-11-21 22:37 UTC, ilrudie commented on GOVERNANCE.md
> +- No single company should cast more than six votes. It is the responsibility of each company to determine which affiliated maintainers will vote.
consider company block voting rather than making the company work out 6 individuals

2024-12-03 16:25 UTC, linsun commented on GOVERNANCE.md
> +- No single company should cast more than six votes. It is the responsibility of each company to determine which affiliated maintainers will vote.
6 similar votes sound good, we have seen a few other successful projects in cncf doing the same.

2024-12-03 16:27 UTC, linsun approved these changes

2024-12-03 18:05 UTC, sam-heilbron approved these changes
LGTM!

2024-12-03 18:05 UTC, sam-heilbron commented on GOVERNANCE.md
> +- A vote is cast when a project maintainer emotes thumbs-up or thumbs-down (👍 or 👎) on the GitHub PR in dispute.
This specifies a GitHub PR. Does this apply to just PRs, or are GitHub issues also subject to votes?

2024-12-03 18:05 UTC, sam-heilbron commented on GOVERNANCE.md
> +- Voting must be open for at least one week or until the required threshold is met.
When is voting considered "open"? From the time a particular issue or PR is opened? Is there a label that indicates which issues are being voted on or is there some other mechanism that I as a maintainer can know which issues are worth voting on? (should I just turn on all notifications for the repository)

2024-12-03 18:05 UTC, sam-heilbron commented on GOVERNANCE.md
> +## Vendor-neutrality
Is there a way to raise a concern about vendor-neutrality should it occur?

2024-12-03 20:27 UTC, danehans commented on GOVERNANCE.md
> +K8sGateway is dedicated to building a feature-rich, fast and flexible ingress controller and next-generation API gateway. This governance document details how the project is run.
Ingress controller that k8sgw supports Ingress. IMHO the project should not support Ingress.

2024-12-03 20:27 UTC, danehans commented on GOVERNANCE.md
> +
nit: Remove extra line

2024-12-03 20:27 UTC, danehans commented on GOVERNANCE.md
> +
Thoughts on including a charter? For example:

## Charter

The Steering Committee is the governing body of k8sgateway project, providing decision-making and oversight pertaining to project bylaws, sub-organizations, financial planning, etc. The Steering Committee is comprised of _____ and will be responsible for the following:

- Defining the project roadmap.
- Defining the project scope.

2024-12-03 21:35 UTC, ilrudie commented on GOVERNANCE.md
> +- A vote is cast when a project maintainer emotes thumbs-up or thumbs-down (👍 or 👎) on the GitHub PR in dispute.
It's a good point. I think the discussion in community meetup today was to move to a "call for vote" issue which is a vanilla issue, has some context about why the vote is called and what is being voted on and has a label which makes it easy to search.

We had some trouble last time I would classify as "what are we voting on" since we voted on a PR, some folks reviewed it and left comments, which is great but not a vote. This lead to a sort of rolling vote problem where the PR was mutating during the vote which is sub-optimal. The "call for vote" issue linking out to the PR probably helps with that.

2024-12-03 21:37 UTC, ilrudie commented on GOVERNANCE.md
> +- Voting must be open for at least one week or until the required threshold is met.
See comment above for context. Voting counts as open when the "call for vote" issue is submitted I think, this gives us a definitive date/time for start which is easy to track.

2024-12-03 21:38 UTC, ilrudie commented on GOVERNANCE.md
> +K8sGateway is dedicated to building a feature-rich, fast and flexible ingress controller and next-generation API gateway. This governance document details how the project is run.
I lifted this straight from somewhere in the project essentially verbatim. I do agree though it's odd verbiage given that we should not support the ingress resource.

2024-12-03 21:40 UTC, ilrudie commented on GOVERNANCE.md
> +
I like the idea, I was really confused at first. I think the example given put me off since we don't want to have a steering committee but I think it's not intended to be actual verbiage adopted.

2024-12-03 21:42 UTC, ilrudie commented on GOVERNANCE.md
> +- A vote is cast when a project maintainer emotes thumbs-up or thumbs-down (👍 or 👎) on the GitHub PR in dispute.
Another plus to this, the issue is basically disposable. If the vote fails we can iterate an open PR or whatever we are voting on and then open a new "call for vote" instead of closing the PR and opening an entire new PR where the review context is lost just because we voted and the vote didn't pass.

2024-12-03 21:54 UTC, ilrudie commented on GOVERNANCE.md
> +- A vote is cast when a project maintainer emotes thumbs-up or thumbs-down (👍 or 👎) on the GitHub PR in dispute.
@danehans, would a "call to vote" generally occur in a central repository or in the repo being worked on? Like should "call to vote" be an org-level label or would those votes always occur in say, community, for convenience of finding all votes later on?

2024-12-03 22:07 UTC, ilrudie commented on GOVERNANCE.md
> +## Vendor-neutrality
I didn't make one. To avoid immediate escalation to the CNCF this is not a bad idea, although I suppose "bring it up with the CNCF" is a defacto option when none is given or when you find the given methods unsuitable.

Should we just have something like "Please raise concerns about neutrality by opening an issue or joining our community meeting." or is that too generic. Mailing list(not security so now we need a second one)? Slack?

2024-12-03 23:00 UTC, ilrudie commented on GOVERNANCE.md
> +
I see some projects have an entire charter.md, would it make sense to break this out into an issue to create a charter.md and then link that back here?

2024-12-03 23:49 UTC, kdorosh approved these changes
very exciting! non-blocking: should we consider a CODEOWNERS that tags a github group that mirrors MAINTAINERS.md? that way we can block changes to governance upon a vote

2024-12-04 02:00 UTC, ilrudie commented
> very exciting! non-blocking: should we consider a CODEOWNERS that tags a github group that mirrors MAINTAINERS.md? that way we can block changes to governance upon a vote

💯yes! https://github.com/k8sgateway/community/issues/21

2024-12-04 02:40 UTC, tjons approved these changes
LGTM! Excited to see this shaping up

2024-12-04 03:10 UTC, ilrudie commented on GOVERNANCE.md
> +
done, also took a pass at fixing these lint type mistakes for the entire repo in #20

2024-12-04 21:44 UTC, ilrudie commented on GOVERNANCE.md
> +## Vendor-neutrality
I did add a little blurb in the same vein as what I posted in the previous comment.

2024-12-04 23:19 UTC, ilrudie commented on GOVERNANCE.md
> +
broken out into #23 to keep scope more limited

2024-12-10 20:08 UTC, linsun commented
Please cast your vote for this PR as of today.

2024-12-10 21:21 UTC, linsun commented
Please cast your vote for this PR as of today. Thanks! @ilrudie @yuval-k @tjons @kdorosh @jenshu @nfuden @danehans etc

2024-12-11 03:34 UTC, kdorosh commented on GOVERNANCE.md
> +* A vote is cast when a project maintainer emotes thumbs-up or thumbs-down (👍 or 👎) on the GitHub "call to vote" issue.
Given that the emote can be changed or removed at any point without any historical view of previous votes, this seems like a risk we may want to address

I think it's safer to have the entire history; have we considered voting using any other format? For example, PR approvals for yes and changes requested for no. This also allows context on why a vote was cast the way it was (perhaps this omission is intentional)

2024-12-11 05:47 UTC, tjons commented on GOVERNANCE.md
> +* A simple majority decides the vote outcome.
Should we require that votes be received from more than one org to pass, in pursuit of the vendor-neutrality objective?

2024-12-11 13:49 UTC, nfuden requested changes

2024-12-11 13:49 UTC, nfuden commented on GOVERNANCE.md
> +* A simple majority decides the vote outcome.
Simple majority of possible votes? 
The problem now is that if there exists a company (such as during this bootstrap phase Solo.io) that has more than the cap of 6 votes this gets a little weird.
I would argue that this should be Simple majority of possible votes and if not we minimally need to expand on this comment.

Ie if there are 16 total maintainers with 8 from org A then there are actually only 14 votes. In this case I would expect 8 valid votes to be able to pass instead of 9.

2024-12-11 13:53 UTC, ilrudie commented on GOVERNANCE.md
> +* A simple majority decides the vote outcome.
Yeah, majority of "eligible votes" is maybe the way to put it?

2024-12-11 14:14 UTC, ilrudie commented on GOVERNANCE.md
> +* A vote is cast when a project maintainer emotes thumbs-up or thumbs-down (👍 or 👎) on the GitHub "call to vote" issue.
Does the risk of this kind of behavior only occur if there is an eligible voter (maintainer) looking to sabotage the project? I don't think this should really be an issue in practice if all maintainers are trustworthy. If all maintainers are not trustworthy we have serious, serious issues.

2024-12-11 14:19 UTC, ilrudie commented on GOVERNANCE.md
> +* A simple majority decides the vote outcome.
For clarity, any vote or a vote in favor from multiple companies?

Consider a vote which ends with:
* company A: 4 up votes
* company B: 1 down vote

Is this a passing vote or a failed vote?

2024-12-11 14:23 UTC, linsun commented on GOVERNANCE.md
> +* A vote is cast when a project maintainer emotes thumbs-up or thumbs-down (👍 or 👎) on the GitHub "call to vote" issue.
Hi @kdorosh thanks for weighing in on this.  We thought about this quite a bit and explored a few options:

1. Open an issue to call for vote and in that issue refer to the PR with a given commit.
2. Call vote directly in the PR, which btw is what the CNCF TOC repo uses to vote on projects as well, see an example: https://github.com/cncf/toc/pull/1473#issuecomment-2526194135. we could look into integrating a vote bot down the road but given we don't often, manual kicking off the vote should be okay.
- in this model, whenever there is a new commit (and you do see the history in the PR!), a new vote should be called with the latest change.
We decided to opt in for the 2nd method because it has everything in one PR and also used by the CNCF TOC repo which does vote a lot.

2024-12-11 14:25 UTC, linsun commented on GOVERNANCE.md
> +* A simple majority decides the vote outcome.
Agreed, it needs to be "eligible votes".

2024-12-11 14:28 UTC, linsun commented on GOVERNANCE.md
> +* A simple majority decides the vote outcome.
```suggestion
* A simple majority of eligible votes decides the vote outcome.
```

2024-12-11 14:30 UTC, linsun commented on GOVERNANCE.md
> +* A simple majority decides the vote outcome.
Updated to be eligible votes which a company can have a max of 6 eligible votes. This does mean it has to get more votes from more than one org to pass based on the eligible voters today.

2024-12-11 14:31 UTC, linsun commented on GOVERNANCE.md
> +* A simple majority decides the vote outcome.
To Ian's question, that is a passing vote in that case. But the issue with your example is the diversity of eligible voters which is why we try to recruit diversified maintainers as much as possible.

2024-12-11 14:35 UTC, linsun commented on GOVERNANCE.md
> +* A vote is cast when a project maintainer emotes thumbs-up or thumbs-down (👍 or 👎) on the GitHub "call to vote" issue.
```suggestion
* A vote is cast when a project maintainer emotes thumbs-up or thumbs-down (👍 or 👎) on a specific "call to vote" comment of the GitHub PR, referring to the most recent commit when the comment is entered. If there is any further commit to the PR, a new vote must be called to refer to the new commit.
```

2024-12-11 14:36 UTC, linsun commented on GOVERNANCE.md
> +* A vote is cast when a project maintainer emotes thumbs-up or thumbs-down (👍 or 👎) on the GitHub "call to vote" issue.
Updated the wording a bit to make it clear, ptal @kdorosh @ilrudie @tjons - thanks!

2024-12-11 14:38 UTC, ilrudie commented on GOVERNANCE.md
> +* A simple majority decides the vote outcome.
I think my example is not so clear cut though. In this case we have 1 consenting company and 1 against. A simple majority is reached, plainly, however if we require 2 companies as suggested what is the outcome of this vote in that case? This is the scenario I'd like to consider. Is it "simple majority and at least 2 companies agree to it" or "simple majority if any 2 companies participate". We should also consider what happens if the vote goes to time with only a single company participating if we want to adopt verbiage around multiple companies...

We shouldn't IMO always assume all eligible voters will vote when considering how the processes will work so my hypothetical is a possible vote outcome for this project, as the maintainer council looks today.

2024-12-11 14:39 UTC, ilrudie commented on GOVERNANCE.md
> +* A vote is cast when a project maintainer emotes thumbs-up or thumbs-down (👍 or 👎) on the GitHub "call to vote" issue.
Looks good. I think this was also implied, but making it explicit is a good idea

2024-12-11 15:00 UTC, linsun commented
Thank you all for the feedback, PTAL of the latest commit (up to ffb74203770c94227f6c233514747ca48edf3114).

2024-12-11 22:33 UTC, kdorosh approved these changes

2024-12-11 22:41 UTC, kdorosh commented on GOVERNANCE.md
> +* A vote is cast when a project maintainer emotes thumbs-up or thumbs-down (👍 or 👎) on the GitHub "call to vote" issue.
I think this works for now because we trust the maintainers. Dissenters can add reason for dissent in the issue as a new comment, so this can always be improved down the road. A vote bot may be preferable to depending on PR review semantics

I see PR review improving two scenarios:
1. Maintainer has a change of heart or is swayed to a new opinion
2. Maintainer has an obvious place to add dissenting reasons 

I care more about 2., but I think both can be improved in the future. I'm not going to block this PR on these improvements

2024-12-11 22:44 UTC, tjons approved these changes

2024-12-11 22:53 UTC, danehans approved these changes
A few nits, otherwise /lgtm

2024-12-11 22:53 UTC, danehans commented on GOVERNANCE.md
> +* A vote begins when a PR that has a comment with the label `up-for-vote` is submitted.
nit: `A vote begins with...`

2024-12-11 22:53 UTC, danehans commented on GOVERNANCE.md
> +* A vote begins when a PR that has a comment with the label `up-for-vote` is submitted.
I thought we decided on using a dedicated GH Issue to call a vote and to xref all necessary issues, PR, etc. that generated the call to vote?

2024-12-11 22:53 UTC, danehans commented on GOVERNANCE.md
> +* Voting must be open for at least one week or until the required threshold is met.
We should set a time limit for a vote.

2024-12-11 22:53 UTC, danehans commented on GOVERNANCE.md
> +* A simple majority of eligible votes decides the vote outcome.
Consider defining "eligible".

2024-12-11 22:53 UTC, danehans commented on GOVERNANCE.md
> +* Any change requires a 2/3 super majority to be accepted.
^ also "eligible" votes?

2024-12-12 20:00 UTC, jenshu commented on GOVERNANCE.md
> +* A vote begins when a PR that has a comment with the label `up-for-vote` is submitted.
per our discussion this week, we thought it was a good idea to call for votes via a comment within a PR, because it easily shows the time at which the vote was taken, and if further commits are pushed after that, it would invalidate the vote and a new vote could be called via a new comment on the PR

2024-12-12 20:02 UTC, jenshu commented on GOVERNANCE.md
> +* A vote begins when a PR that has a comment with the label `up-for-vote` is submitted.
what does "a comment with the label `up-for-vote`" mean? maybe it meant to say that the PR (not the comment) contains the label?

there seems to also be a label called `do-not-merge/vote-needed` which seems similar to the other, do we need both?

2024-12-12 20:05 UTC, jenshu commented on GOVERNANCE.md
> +* A vote begins when a PR that has a comment with the label `up-for-vote` is submitted.
can we also be specific on how a call for vote is initiated via a comment? does the comment need to contain specific text, or just something to indicate that they are calling for a vote?

2024-12-12 20:06 UTC, jenshu commented on GOVERNANCE.md
> +* Voting must be open for at least one week or until the required threshold is met.
```suggestion
* Voting must be open for at least one week or until the required threshold is met, whichever is sooner.
```

2024-12-12 20:08 UTC, jenshu commented on GOVERNANCE.md
> +* Any change requires a 2/3 super majority to be accepted.
is this also max 6 votes per company?

2024-12-12 21:40 UTC, linsun commented on GOVERNANCE.md
> +* A vote begins when a PR that has a comment with the label `up-for-vote` is submitted.
BTW, we have a vote bot integrated now, following CNCF TOC's best practice :). You can see a test issue here: https://github.com/k8sgateway/community/issues/39

2024-12-12 21:41 UTC, linsun commented on GOVERNANCE.md
> +* A vote begins when a PR that has a comment with the label `up-for-vote` is submitted.
Re [nit: A vote begins with...

> nit: `A vote begins with...`](nit: A vote begins with...), might be my english, i really think it is `when` here because it is a sentence after it.

2024-12-12 21:42 UTC, linsun commented on GOVERNANCE.md
> +* Voting must be open for at least one week or until the required threshold is met.
Yes it is set to a week, see https://github.com/k8sgateway/community/blob/main/.gitvote.yml

2024-12-12 21:42 UTC, linsun commented on GOVERNANCE.md
> +* A simple majority of eligible votes decides the vote outcome.
It is currently defined in github as a group - see https://github.com/k8sgateway/community/blob/main/.gitvote.yml

2024-12-12 21:44 UTC, linsun commented on GOVERNANCE.md
> +* Any change requires a 2/3 super majority to be accepted.
Yes.

2024-12-12 21:52 UTC, linsun commented on GOVERNANCE.md
> +* Any change requires a 2/3 super majority to be accepted.
I clarified eligible voters earlier, i think this is strongly implied.

2024-12-12 21:53 UTC, linsun commented on GOVERNANCE.md
> +* A vote begins when a PR that has a comment with the label `up-for-vote` is submitted.
Updated, PTAL @jenshu @ilrudie

2024-12-12 22:14 UTC, ilrudie commented on GOVERNANCE.md
> +* A vote is cast when a project maintainer emotes thumbs-up or thumbs-down (👍 or 👎) on the specific "vote" created by the git-vote bot of the GitHub PR, referring to the most recent commit when the v
```suggestion
* A vote is cast when a project maintainer emotes thumbs-up or thumbs-down (👍 or 👎) on the specific "vote" created by the git-vote bot on the GitHub PR, referring to the most recent commit when the vote is created. If there is any further commit to the PR, a new vote must be created.
```

2024-12-12 22:16 UTC, jenshu commented on GOVERNANCE.md
> +* A vote begins when a PR that has the `/vote` comment.
```suggestion
* A vote begins when someone adds a PR comment containing the `/vote` command.
```

2024-12-12 22:17 UTC, jenshu commented on GOVERNANCE.md
> +* A vote is cast when a project maintainer emotes thumbs-up or thumbs-down (👍 or 👎) on the specific "vote" created by the git-vote bot of the GitHub PR, referring to the most recent commit when the v
```suggestion
* A vote is cast when a project maintainer emotes thumbs-up or thumbs-down (👍 or 👎) on the specific "vote" created by the git-vote bot of the GitHub PR, referring to the most recent commit at the time the vote is created. If there is any further commit to the PR, a new vote must be created.
```

2024-12-12 22:23 UTC, ilrudie commented on GOVERNANCE.md
> +* [ROLES.md](./ROLES.md) for the different roles with the project.
roles is gone now on the tip of main. it's contrib-ladder now @linsun should I handle the rebase and update this or do you want to?

2024-12-12 22:32 UTC, linsun commented on GOVERNANCE.md
> +* [ROLES.md](./ROLES.md) for the different roles with the project.
I got it : good eye catch!

2024-12-12 22:34 UTC, linsun commented on GOVERNANCE.md
> +* A vote is cast when a project maintainer emotes thumbs-up or thumbs-down (👍 or 👎) on the specific "vote" created by the git-vote bot of the GitHub PR, referring to the most recent commit when the v
Applied manually

2024-12-12 22:34 UTC, linsun commented on GOVERNANCE.md
> +* [ROLES.md](./ROLES.md) for the different roles with the project.
updated

2024-12-12 22:35 UTC, linsun commented
/vote

2024-12-13 01:29 UTC, jenshu approved these changes

2024-12-16 16:46 UTC, ilrudie commented
/check-vote

2024-12-16 16:49 UTC, ilrudie commented
@kdorosh, our bot is listing your vote as "non-binding" because your invite to the "eligible-voters" team hasn't been accepted yet

2024-12-17 00:22 UTC, kdorosh commented
@ilrudie I just accepted the invite to the k8sgateway github organization, which I think should resolve the issue. thanks for the heads up!

2024-12-17 14:45 UTC, linsun commented
/check-vote

2024-12-17 17:23 UTC, linsun commented
/check-vote

2024-12-17 17:24 UTC, linsun commented
Going to go ahead and merge this PR given the vote has passed with 90%!! Thank you everyone for voting!!

2024-12-17 17:24 UTC, merged